#!/usr/bin/python3
import socket
sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = 3000
sockmod.settimeout(timeout)
hostip = input("What Ip address? ")
port = input("What Port? ")
def portScanner(portno):
    if sockmod.bind((hostip, int(portno))): # TODO: Replace "FUNCTION" with the appropriate socket.function call as found in the [socket docs](https://docs.python.org/3/library/socket.html)
        print("Port closed")
    else:
        print("Port open")
portScanner(port)
