#!/usr/bin/env python3
#------------------------------------------------------#
# Script Name                Ops challenge 37
# Author                     Kimberley Cabrera-Boggs
# Date of last revision      November 24, 2020
# Description of purpose     Cookie Capture 
#------------------------------------------------------#
print("""
 ██████  ██████   ██████  ██   ██ ██ ███████      ██████  █████  ██████  ████████ ██    ██ ██████  ███████ 
██      ██    ██ ██    ██ ██  ██  ██ ██          ██      ██   ██ ██   ██    ██    ██    ██ ██   ██ ██      
██      ██    ██ ██    ██ █████   ██ █████       ██      ███████ ██████     ██    ██    ██ ██████  █████   
██      ██    ██ ██    ██ ██  ██  ██ ██          ██      ██   ██ ██         ██    ██    ██ ██   ██ ██      
 ██████  ██████   ██████  ██   ██ ██ ███████      ██████ ██   ██ ██         ██     ██████  ██   ██ ███████ 

              .---. .---. 
             :     : o   :    me want cookie!
         _..-:   o :     :-.._    /
     .-''  '  `---' `---' "   ``-.    
   .'   "   '  "  .    "  . '  "  `.  
  :   '.---.,,.,...,.,.,.,..---.  ' ;
  `. " `.                     .' " .'
   `.  '`.                   .' ' .'
    `.    `-._           _.-' "  .'  .----.
      `. "    '"--...--"'  . ' .'  .'  o   `.
      .'`-._'    " .     " _.-'`. :       o  :
    .'      ```--.....--'''    ' `:_ o       :
  .'    "     '         "     "   ; `.;";";";'
 ;         '       "       '     . ; .' ; ; ;
;     '         '       '   "    .'      .-'
'  "     "   '      "           "    _.-'

""")
#----------------------Import Libraries----------------#
import os
import requests
#--------------------------Function--------------------#
url = input("Enter target site:") 
response = requests.get(url)
myFirstcookie = response.cookies
print(response.cookies)

# Send the cookie back to the site and receive a HTTP response
cookiemonsterhtml = requests.get(targetsite, cookies=cookie)
website = cookiemonsterhtml.text

# Generate a .html file to capture the contents of the HTTP response
with open ('cookiemonster.html', 'w') as file:file.write(website)

# Print to screen that website is opening
print("mmmm, num num me like cookie...")

# Open it with Firefox
os.system("firefox /home/osboxes/cookiemonster.html")
