#!/user/bin/env python3
#----------------------------------------------------------------#
# Script Name                Ops Challenge 11
# Author                     Kimberley Cabrera-Boggs
# Date of last revision      October 19, 2020
# Description of purpose     Network Security Tool w/Scapy Part 1
#----------------------------------------------------------------#
#   ,-~~-.___.
#  / |  '     \
# (  )         0
#  \_/-, ,----'
#     ====           //
#    /  \-'~;    /~~~(O)
#   /  __/~|   /       |
# =(  _____| (_________|

# Import Libraries
import socket
import random
import colorama 
import scapy.all as scapy
from datetime import datetime

# Host to scan
host = input("Enter Source Destination Here")
print(host)
ip = socket.gethostbyname(host) 

print("-" * 80)
print("              Please wait, Scanning the host -----------> ", ip)
print("-" * 80)

rand_num = random.randint(0,9)

# Start time
t1 = datetime.now()
port_list=[21,22,23]

# Scanning ports
try: 
    for port in port_list:
        sock = socket.socket (socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex((ip,port))
        if result == 0:
            # If the socket is listening print the port number
            print("\n Port %d Is Open ----------> " %(port))
            sock.close()
        else: 
            print ("\n Port %d Is Close :-(" %(port))
except:
    pass

# Calculate end of execute time
t2 = datetime.now()
# Calculate difference
total =t2 - t1
# Print difference
print("Total Scanning Time : ",total)
