#!/usr/bin/env python3
#------------------------------------------------------#
# Script Name                Ops challenge 37
# Author                     Kimberley Cabrera-Boggs
# Date of last revision      November 24, 2020
# Description of purpose     Cookie Capture 
#------------------------------------------------------#
print("""
 ██████  ██████   ██████  ██   ██ ██ ███████      ██████  █████  ██████  ████████ ██    ██ ██████  ███████ 
██      ██    ██ ██    ██ ██  ██  ██ ██          ██      ██   ██ ██   ██    ██    ██    ██ ██   ██ ██      
██      ██    ██ ██    ██ █████   ██ █████       ██      ███████ ██████     ██    ██    ██ ██████  █████   
██      ██    ██ ██    ██ ██  ██  ██ ██          ██      ██   ██ ██         ██    ██    ██ ██   ██ ██      
 ██████  ██████   ██████  ██   ██ ██ ███████      ██████ ██   ██ ██         ██     ██████  ██   ██ ███████ 

              .---. .---. 
             :     : o   :    me want cookie!
         _..-:   o :     :-.._    /
     .-''  '  `---' `---' "   ``-.    
   .'   "   '  "  .    "  . '  "  `.  
  :   '.---.,,.,...,.,.,.,..---.  ' ;
  `. " `.                     .' " .'
   `.  '`.                   .' ' .'
    `.    `-._           _.-' "  .'  .----.
      `. "    '"--...--"'  . ' .'  .'  o   `.
      .'`-._'    " .     " _.-'`. :       o  :
    .'      ```--.....--'''    ' `:_ o       :
  .'    "     '         "     "   ; `.;";";";'
 ;         '       "       '     . ; .' ; ; ;
;     '         '       '   "    .'      .-'
'  "     "   '      "           "    _.-'

""")
#----------------------Import Libraries----------------#
import requests
#--------------------------Function--------------------#
url = input("Enter target site:") 
response = requests.get(url)
myFirstcookie = response.cookies
print(response.cookies)

# Send the cookie back to the site and receive a HTTP response
cookies_jar = requests.cookies.RequestsCookieJar()
session = requests.session()
print(session)

# Generate a .html file to capture the contents of the HTTP response

receive = requests.get('https://www.google.com')
with open(r'cookie.html','wb') as f:
    f.write(receive.content)

# Open it with Firefox
