#!/user/bin/env python3
#------------------------------------------------------#
# Script Name                Ops Challenge 31
# Author                     Kimberley Cabrera-Boggs
# Date of last revision      November 16, 2020
# Description of purpose     Malware Detection Part 1
#------------------------------------------------------#
print("""
███╗   ███╗ █████╗ ██╗     ██╗    ██╗ █████╗ ██████╗ ███████╗    
████╗ ████║██╔══██╗██║     ██║    ██║██╔══██╗██╔══██╗██╔════╝    
██╔████╔██║███████║██║     ██║ █╗ ██║███████║██████╔╝█████╗      
██║╚██╔╝██║██╔══██║██║     ██║███╗██║██╔══██║██╔══██╗██╔══╝      
██║ ╚═╝ ██║██║  ██║███████╗╚███╔███╔╝██║  ██║██║  ██║███████╗    
╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝    
                                                                 
██████╗ ███████╗████████╗███████╗ ██████╗████████╗██╗ ██████╗ ███╗   ██╗
██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║
██║  ██║█████╗     ██║   █████╗  ██║        ██║   ██║██║   ██║██╔██╗ ██║
██║  ██║██╔══╝     ██║   ██╔══╝  ██║        ██║   ██║██║   ██║██║╚██╗██║
██████╔╝███████╗   ██║   ███████╗╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║
╚═════╝ ╚══════╝   ╚═╝   ╚══════╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ 
Part 1                                                                     
""")
#----------------------Import Libraries----------------#
import os
import glob
#-------------------------Variable---------------------#
# Prompt the user to type in a file name to search for.
fileName = input("What file are you searching for? ")
# Prompt the user for a directory to search in.
dirName = input("What directory should I get that file from? ")
#-------------------------Function---------------------#
# Search each file in the directory by name
for file in os.listdir('C:\\users\kimbe\\'+ dirName):
    print(os.path.join(dirName, file))
# For each positive detection, print file name and location.
print(fileName, dirName)
# Print how many files were searched and how many hits were found
path = r'C:\\users\kimbe'
count = 0
l = os.listdir(path)
print(l)
count += 1
print(count)
g = glob.glob('*.py')
print(g)
